stages:
  - build
  - test
  - dockerize

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/tjv-projekt
  JAR_FILE: build/libs/blogclient-0.0.1-SNAPSHOT.jar

build:
  only:
    - main
  stage: build
  image: gradle:7.6-jdk21
  script:
    - echo "Building Java application with Gradle and OpenJDK 21..."
    - gradle clean build -x test
  artifacts:
    paths:
      - build/libs

test:
  only:
    - main
  stage: test
  image: gradle:7.6-jdk21
  script:
    - echo "Running tests with Gradle and OpenJDK 21..."
    - gradle test

dockerize:
  stage: dockerize
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  before_script:
    - echo "Logging in to Docker registry..."
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - echo "Pushing Docker image to registry..."
    - docker push $DOCKER_IMAGE
  only:
    - main
